# Rubhini - HOPE AI Student

# Python RealTime Facebook Advertisements Project

 ## 1. Loading the libraries needed

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from IPython.display import FileLink

## 2. Loading the facebook_ad dataset

In [2]:
fb_ds=pd.read_csv("fb_data.csv")

In [3]:
fb_ds.head()

,Campaign name,Day,Delivery status,Delivery level,Amount spent (INR),Impressions,"CPM (cost per 1,000 impressions)",Reach,Frequency,CTR (link click-through rate),...,CTR (all),Link clicks,Landing page views,Result Type,Results,Purchase ROAS (return on ad spend),Attribution setting,Cost per result,Reporting starts,Reporting ends
0,ForeignSales-AsiaAntartrica,3/31/2024,active,campaign,1033.89,21966,47.06774,20810,1.055550,0.883183,...,1.884731,194.0,91.0,freewebinarThankyoupage,9.0,NaN,7-day click or 1-day view,114.8767,3/31/2024,3/31/2024
1,Feedbackrs9,3/31/2024,inactive,campaign,497.70,5774,86.19674,5590,1.032916,0.381018,...,0.865951,22.0,14.0,NaN,1.0,NaN,7-day click or 1-day view,NaN,3/31/2024,3/31/2024
2,ForeignSales-AsiaAntartrica,3/29/2024,active,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,freewebinarThankyoupage,1.0,NaN,7-day click or 1-day view,0.0000,3/29/2024,3/29/2024
3,Feedbackrs9,3/28/2024,inactive,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7-day click or 1-day view,NaN,3/28/2024,3/28/2024
4,ForeignSales-AsiaAntartrica,3/27/2024,active,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,freewebinarThankyoupage,1.0,NaN,7-day click or 1-day view,0.0000,3/27/2024,3/27/2024

## 3.Taking out the columns needed

In [4]:
columns_to_keep = ['Campaign name', 'Day', 'Amount spent (INR)', 'CTR (link click-through rate)', 'Link clicks','Landing page views','Results']
fb_ds = fb_ds.loc[:, columns_to_keep]

In [5]:
fb_ds.head(4)

,Campaign name,Day,Amount spent (INR),CTR (link click-through rate),Link clicks,Landing page views,Results
0,ForeignSales-AsiaAntartrica,3/31/2024,1033.89,0.883183,194.0,91.0,9.0
1,Feedbackrs9,3/31/2024,497.70,0.381018,22.0,14.0,1.0
2,ForeignSales-AsiaAntartrica,3/29/2024,0.00,NaN,NaN,NaN,1.0
3,Feedbackrs9,3/28/2024,0.00,NaN,NaN,NaN,NaN

## 3.a. Renaming the columns

In [6]:
fb_ds.rename(columns={'Day':'Date','Campaign name': 'Campaign','Delivery status':'Status','Amount spent (INR)':'Ad Spent',
                      'CTR (link click-through rate)':'CTR','Landing page views':'LP Views','Results':'No.of leads'},inplace=True)

## 4.Getting information about the dataset

In [7]:
fb_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Campaign     46 non-null     object
 1   Date         46 non-null     object
 2   Ad Spent     46 non-null     float64
 3   CTR          26 non-null     float64
 4   Link clicks  26 non-null     float64
 5   LP Views     26 non-null     float64
 6   No.of leads  29 non-null     float64
dtypes: float64(5), object(2)
memory usage: 2.6+ KB

## 5. Working with DateType column

In [8]:
fb_ds['Date'] =fb_ds['Date'].str.replace('/', '-')

In [9]:
fb_ds['Date'] = pd.to_datetime(fb_ds['Date'])

In [10]:
fb_ds['Date'].dtype

dtype('<M8[ns]')

In [11]:
def format_date(Date):
    # Format the date as desired (e.g., "1 Mar(Mon)")
        date_obj = pd.to_datetime(Date, format='%m/%d/%y')
        formatted_date = date_obj.strftime('%d %b(%a)')
        return formatted_date

In [12]:
fb_ds['Date'] = fb_ds['Date'].apply(format_date)

In [13]:
fb_ds.head()

,Campaign,Date,Ad Spent,CTR,Link clicks,LP Views,No.of leads
0,ForeignSales-AsiaAntartrica,31 Mar(Sun),1033.89,0.883183,194.0,91.0,9.0
1,Feedbackrs9,31 Mar(Sun),497.70,0.381018,22.0,14.0,1.0
2,ForeignSales-AsiaAntartrica,29 Mar(Fri),0.00,NaN,NaN,NaN,1.0
3,Feedbackrs9,28 Mar(Thu),0.00,NaN,NaN,NaN,NaN
4,ForeignSales-AsiaAntartrica,27 Mar(Wed),0.00,NaN,NaN,NaN,1.0

## 6.Checking for null values in the dataset

In [14]:
fb_ds.isnull().sum()

Campaign        0
Date            0
Ad Spent        0
CTR            20
Link clicks    20
LP Views       20
No.of leads    17
dtype: int64

In [15]:
fb_ds['CTR'].unique()

array([0.883183, 0.381018,      nan, 1.079308, 0.470656, 0.402319,
       0.733471, 0.858479, 0.410152, 0.933209, 0.501151, 0.802902,
       0.430429, 0.643808, 0.739839, 1.497326, 0.540239, 2.142501,
       0.668271, 2.406903, 2.539405, 3.756345, 0.999303, 0.641026,
       0.990656, 1.472565, 0.973532])

In [16]:
#Replace the null value with 0
fb_ds.fillna({'CTR':0},inplace=True)

In [17]:
fb_ds.fillna({'Link clicks':0},inplace=True)

In [18]:
fb_ds.fillna({'LP Views':0},inplace=True)

In [19]:
fb_ds.fillna({'No.of leads':0},inplace=True)

In [20]:
fb_ds.tail(8)

,Campaign,Date,Ad Spent,CTR,Link clicks,LP Views,No.of leads
38,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,03 Mar(Sun),1520.26,0.999303,129.0,99.0,8.0
39,3dayslive â€“ Copy,03 Mar(Sun),0.00,0.000000,0.0,0.0,0.0
40,Foreign|Sales|Tamil,03 Mar(Sun),0.00,0.000000,0.0,0.0,3.0
41,Foreign|Sales|Tamil,02 Mar(Sat),384.46,0.641026,18.0,8.0,3.0
42,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,02 Mar(Sat),1896.02,0.990656,176.0,135.0,5.0
43,3dayslive â€“ Copy,01 Mar(Fri),0.00,0.000000,0.0,0.0,1.0
44,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,01 Mar(Fri),1899.99,1.472565,252.0,209.0,12.0
45,Foreign|Sales|Tamil,01 Mar(Fri),484.26,0.973532,32.0,18.0,0.0

## 7. Including additional metric columns

In [21]:
#funtion to create columns with calculated values
def calculate_additional_columns(ds):
    # Calculate additional columns
    ds = ds.assign(Cost_per_Lead=lambda x: (x['Ad Spent'] / x['No.of leads']),
        Member_Passed =lambda x: (x['LP Views'] / x['Link clicks']) * 100,
        LP_Conversion=lambda x: (x['No.of leads'] / x['LP Views']) * 100
    )
    return ds

In [22]:
fb_ds=calculate_additional_columns(fb_ds)

In [23]:
fb_ds.head(5)

,Campaign,Date,Ad Spent,CTR,Link clicks,LP Views,No.of leads,Cost_per_Lead,Member_Passed,LP_Conversion
0,ForeignSales-AsiaAntartrica,31 Mar(Sun),1033.89,0.883183,194.0,91.0,9.0,114.876667,46.907216,9.890110
1,Feedbackrs9,31 Mar(Sun),497.70,0.381018,22.0,14.0,1.0,497.700000,63.636364,7.142857
2,ForeignSales-AsiaAntartrica,29 Mar(Fri),0.00,0.000000,0.0,0.0,1.0,0.000000,NaN,inf
3,Feedbackrs9,28 Mar(Thu),0.00,0.000000,0.0,0.0,0.0,NaN,NaN,NaN
4,ForeignSales-AsiaAntartrica,27 Mar(Wed),0.00,0.000000,0.0,0.0,1.0,0.000000,NaN,inf

In [24]:
fb_ds.fillna(0,inplace=True)

## 8. GroupBy Campaign Name

In [25]:
def get_sorted_campaign_names(fb_ds):
    # Group by 'Campaign' and find the first date of each campaign
    first_dates = fb_ds.groupby('Campaign')['Date'].min().reset_index()
    
    # Sort campaigns based on the first date
    first_dates_sorted = first_dates.sort_values(by='Date')
    
    # Get the sorted campaign names
    sorted_campaign_names = first_dates_sorted['Campaign'].tolist()
    
    return sorted_campaign_names

In [26]:
sorted_campaign_names=get_sorted_campaign_names(fb_ds)

## 8.a.Creating Campaign_wise dataframe

In [27]:
def createCampaign_data(fb_ds):
    campaigns_list=[]
    for campaign in sorted_campaign_names:
        camp_df=fb_ds[fb_ds['Campaign']==campaign].copy()
        camp_df = camp_df.sort_values(by='Date')
        campaigns_list.append(camp_df)
        campaignwise_df = pd.concat(campaigns_list, ignore_index=True)
    return campaignwise_df

In [28]:
campaignwise_df=createCampaign_data(fb_ds)

In [29]:
campaignwise_df

,Campaign,Date,Ad Spent,CTR,Link clicks,LP Views,No.of leads,Cost_per_Lead,Member_Passed,LP_Conversion
0,3dayslive â€“ Copy,01 Mar(Fri),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
1,3dayslive â€“ Copy,03 Mar(Sun),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
2,3dayslive â€“ Copy,04 Mar(Mon),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
3,3dayslive â€“ Copy,05 Mar(Tue),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
4,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,01 Mar(Fri),1899.99,1.472565,252.0,209.0,12.0,158.332500,82.936508,5.741627
5,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,02 Mar(Sat),1896.02,0.990656,176.0,135.0,5.0,379.204000,76.704545,3.703704
6,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,03 Mar(Sun),1520.26,0.999303,129.0,99.0,8.0,190.032500,76.744186,8.080808
7,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,04 Mar(Mon),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
8,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,05 Mar(Tue),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
9,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,06 Mar(Wed),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
10,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,07 Mar(Thu),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
11,3dayslive â€“ Copy 2 - Advantage+ shopping campaign,08 Mar(Fri),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
12,Foreign|Sales|Tamil,01 Mar(Fri),484.26,0.973532,32.0,18.0,0.0,inf,56.250000,0.000000
13,Foreign|Sales|Tamil,02 Mar(Sat),384.46,0.641026,18.0,8.0,3.0,128.153333,44.444444,37.500000
14,Foreign|Sales|Tamil,03 Mar(Sun),0.00,0.000000,0.0,0.0,3.0,0.000000,0.000000,inf
15,Foreign|Sales|Tamil,04 Mar(Mon),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
16,Foreign|Sales|Tamil,06 Mar(Wed),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
17,Foreign|Sales|Tamil - Advantage+ shopping camp...,03 Mar(Sun),391.27,3.756345,37.0,30.0,0.0,inf,81.081081,0.000000
18,Foreign|Sales|Tamil - Advantage+ shopping camp...,16 Mar(Sat),403.43,2.539405,29.0,22.0,0.0,inf,75.862069,0.000000
19,Foreign|Sales|Tamil - Advantage+ shopping camp...,17 Mar(Sun),681.39,2.406903,53.0,40.0,0.0,inf,75.471698,0.000000
20,Foreign|Sales|Tamil - Advantage+ shopping camp...,18 Mar(Mon),705.63,2.142501,43.0,36.0,0.0,inf,83.720930,0.000000
21,Foreign|Sales|Tamil - Advantage+ shopping camp...,19 Mar(Tue),300.96,1.497326,14.0,12.0,0.0,inf,85.714286,0.000000
22,Foreign|Sales|Tamil - Advantage+ shopping camp...,21 Mar(Thu),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
23,Foreign|Sales|Tamil - Advantage+ shopping camp...,22 Mar(Fri),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
24,Feedbackrs9,17 Mar(Sun),1941.11,0.668271,100.0,80.0,21.0,92.433810,80.000000,26.250000
25,Feedbackrs9,18 Mar(Mon),2001.02,0.540239,97.0,63.0,10.0,200.102000,64.948454,15.873016
26,Feedbackrs9,19 Mar(Tue),2009.33,0.643808,135.0,87.0,18.0,111.629444,64.444444,20.689655
27,Feedbackrs9,20 Mar(Wed),1997.54,0.430429,92.0,75.0,11.0,181.594545,81.521739,14.666667
28,Feedbackrs9,21 Mar(Thu),1982.31,0.501151,111.0,90.0,20.0,99.115500,81.081081,22.222222
29,Feedbackrs9,22 Mar(Fri),1983.00,0.410152,101.0,71.0,11.0,180.272727,70.297030,15.492958
30,Feedbackrs9,23 Mar(Sat),1941.17,0.402319,102.0,72.0,15.0,129.411333,70.588235,20.833333
31,Feedbackrs9,24 Mar(Sun),1573.42,0.470656,98.0,65.0,5.0,314.684000,66.326531,7.692308
32,Feedbackrs9,26 Mar(Tue),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
33,Feedbackrs9,28 Mar(Thu),0.00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
34,Feedbackrs9,31 Mar(Sun),497.70,0.381018,22.0,14.0,1.0,497.700000,63.636364,7.142857
35,ForeignSales-AsiaAntartrica,19 Mar(Tue),662.74,0.739839,79.0,50.0,2.0,331.370000,63.291139,4.000000
36,ForeignSales-AsiaAntartrica,20 Mar(Wed),973.36,0.802902,135.0,102.0,4.0,243.340000,75.555556,3.921569
37,ForeignSales-AsiaAntartrica,21 Mar(Thu),954.40,0.933209,140.0,74.0,3.0,318.133333,52.857143,4.054054
38,ForeignSales-AsiaAntartrica,22 Mar(Fri),991.47,0.858479,134.0,76.0,0.0,inf,56.716418,0.000000
39,ForeignSales-AsiaAntartrica,23 Mar(Sat),964.12,0.733471,139.0,98.0,4.0,241.030000,70.503597,4.081633
40,ForeignSales-AsiaAntartrica,24 Mar(Sun),815.22,1.079308,181.0,97.0,6.0,135.870000,53.591160,6.185567
41,ForeignSales-AsiaAntartrica,25 Mar(Mon),0.00,0.000000,0.0,0.0,4.0,0.000000,0.000000,inf
42,ForeignSales-AsiaAntartrica,26 Mar(Tue),0.00,0.000000,0.0,0.0,3.0,0.000000,0.000000,inf
43,ForeignSales-AsiaAntartrica,27 Mar(Wed),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
44,ForeignSales-AsiaAntartrica,29 Mar(Fri),0.00,0.000000,0.0,0.0,1.0,0.000000,0.000000,inf
45,ForeignSales-AsiaAntartrica,31 Mar(Sun),1033.89,0.883183,194.0,91.0,9.0,114.876667,46.907216,9.890110

## 8.b. Campaign_wise .csv file

In [30]:
def create_campaignwise_csv(ds):
    # Take user input for campaign name
    campaign_name_input = input("Enter Campaign Name: ")
    # Convert input to lowercase
    campaign_name_input_lower = campaign_name_input.lower()
    # Filter DataFrame based on the given campaign name (case-insensitive)
    campaignwise_df = ds[ds['Campaign'].str.lower() == campaign_name_input_lower].copy()
    # Check if any data found for the entered campaign name
    if not campaignwise_df.empty:
        csv_filename = f"{campaign_name_input_lower}_data.csv"
        # Save the campaign-wise DataFrame to a CSV file
        campaignwise_df.to_csv(csv_filename,encoding='utf-8', index=False)
        file_link = FileLink(csv_filename, result_html_prefix="Click here to download: ")
        # Display the download link
        display(file_link)
    else:
        print("No data found for the entered campaign name.")

In [33]:
create_campaignwise_csv(campaignwise_df)

Enter Campaign Name:  ForeignSales-AsiaAntartrica

D:\Hope AI\InternshipProjects\PythonRealTime_FacebookAd\foreignsales-asiaantartrica_data.csv